import argparse
import json
import os
from modules.paths_internal import normalized_filepath, models_path, script_path, data_path, extensions_dir, extensions_builtin_dir, sd_default_config, sd_model_file  # noqa: F401

parser = argparse.ArgumentParser()

parser.add_argument("-f", action='store_true', help=argparse.SUPPRESS)  # allows running as root; implemented outside of webui
parser.add_argument("--update-all-extensions", action='store_true', help="launch.py 引数:プログラム起動時にすべての拡張機能のアップデートをダウンロードしてください")
parser.add_argument("--skip-python-version-check", action='store_true', help="launch.py 引数: pythonバージョンを確認しない")
parser.add_argument("--skip-torch-cuda-test", action='store_true', help="launch.py 引数: CUDAが正常に動作するか確認しない")
parser.add_argument("--reinstall-xformers", action='store_true', help="launch.py 引数: 既にインストールされているバージョンであっても、適切なバージョンのxformersをインストールする")
parser.add_argument("--reinstall-torch", action='store_true', help="launch.py 引数: 既にインストールされているバージョンであっても、適切なバージョンのtorchをインストールする")
parser.add_argument("--update-check", action='store_true', help="launch.py 引数: 起動時に更新を確認する")
parser.add_argument("--test-server", action='store_true', help="launch.py 引数: テスト用にサーバーを構成する")
parser.add_argument("--log-startup", action='store_true', help="launch.py 引数: 起動時の詳細なログを出力する")
parser.add_argument("--skip-prepare-environment", action='store_true', help="launch.py 引数: すべての環境準備をスキップする")
parser.add_argument("--skip-install", action='store_true', help="launch.py 引数: パッケージのインストールをスキップする")
parser.add_argument("--dump-sysinfo", action='store_true', help="launch.py 引数: 拡張機能とオプションの情報なしで制限されたシステム情報ファイルをディスクにダンプして終了する")
parser.add_argument("--loglevel", type=str, help="ログレベル。CRITICAL、ERROR、WARNING、INFO、DEBUG のいずれか", default=None)
parser.add_argument("--do-not-download-clip", action='store_true', help="launch.py 引数: チェックポイントに含まれていない場合でもCLIPモデルをダウンロードしない")
parser.add_argument("--ckpt", type=normalized_filepath, default=sd_model_file, help="Stable Diffusion モデルのチェックポイントへのパス。指定したチェックポイントは一覧に追加され、読み込まれます",)
parser.add_argument("--ckpt-dir", type=normalized_filepath, default=None, help="Stable Diffusion チェックポイントのあるディレクトリへのパス")
parser.add_argument("--vae-dir", type=normalized_filepath, default=None, help="VAE ファイルのあるディレクトリへのパス")
parser.add_argument("--gfpgan-dir", type=normalized_filepath, help="GFPGAN ディレクトリ", default=('./src/gfpgan' if os.path.exists('./src/gfpgan') else './GFPGAN'))
parser.add_argument("--gfpgan-model", type=normalized_filepath, help="GFPGAN モデルのファイル名", default=None)
parser.add_argument("--no-half", action='store_true', help="launch.py 引数: モデルを16-bit floatに切り替えない")
parser.add_argument("--no-half-vae", action='store_true', help="launch.py 引数: VAEモデルを16-bit floatに切り替えない")
parser.add_argument("--no-progressbar-hiding", action='store_true', help="launch.py 引数: gradio UIのプログレスバーを非表示にしない (ブラウザでハードウェアアクセラレーションを使用している場合、MLの速度が低下するため非表示にします)")
parser.add_argument("--max-batch-count", type=int, default=16, help="launch.py 引数: 何もしません")
parser.add_argument("--embeddings-dir", type=normalized_filepath, default=os.path.join(data_path, 'embeddings'), help="launch.py 引数: テキストインバージョン用の埋め込みディレクトリ (デフォルト: embeddings)")
parser.add_argument("--textual-inversion-templates-dir", type=normalized_filepath, default=os.path.join(script_path, 'textual_inversion_templates'), help="launch.py 引数: テキストインバージョンテンプレートのディレクトリ")
parser.add_argument("--hypernetwork-dir", type=normalized_filepath, default=os.path.join(models_path, 'hypernetworks'), help="launch.py 引数: ハイパーネットワークのディレクトリ")
parser.add_argument("--localizations-dir", type=normalized_filepath, default=os.path.join(script_path, 'localizations'), help="launch.py 引数: ローカライズファイルのディレクトリ")
parser.add_argument("--allow-code", action='store_true', help="launch.py 引数: webuiからのカスタムスクリプト実行を許可する")
parser.add_argument("--medvram", action='store_true', help="launch.py 引数: 低VRM使用量のためのstable diffusionモデル最適化を有効にする")
parser.add_argument("--medvram-sdxl", action='store_true', help="launch.py 引数: SDXLモデル専用の--medvram最適化を有効にする")
parser.add_argument("--lowvram", action='store_true', help="launch.py 引数: 非常に低いVRM使用量のためのstable diffusionモデル最適化を有効にする")
parser.add_argument("--lowram", action='store_true', help="launch.py 引数: stable diffusion checkpoint weightsをRAMではなくVRAMにロードする")
parser.add_argument("--always-batch-cond-uncond", action='store_true', help="launch.py 引数: 何もしません")
parser.add_argument("--unload-gfpgan", action='store_true', help="launch.py 引数: 何もしません.")
parser.add_argument("--precision", type=str, help="launch.py 引数: この精度で評価する", choices=["full", "half", "autocast"], default="autocast")
parser.add_argument("--upcast-sampling", action='store_true', help="launch.py 引数: アップキャストサンプリング。効果はゼロ――半分なし。通常は--no-halfと似た結果を出し、より少ないメモリでより良いパフォーマンスを得られます。")
parser.add_argument("--share", action='store_true', help="launch.py 引数: gradio で share=True を使用し、UI を Gradio のサイトからアクセスできるようにする")
parser.add_argument("--ngrok", type=str, help="launch.py 引数: ngrok の認証トークン。--share の代替", default=None)
parser.add_argument("--ngrok-region", type=str, help="launch.py 引数: 何も起こらない。", default="")
parser.add_argument("--ngrok-options", type=json.loads, help='launch.py 引数: ngrokにJSON形式で渡すオプション、例えば: \'{"authtoken_from_env":true, "basic_auth":"user:password", "oauth_provider":"google", "oauth_allow_emails":"user@asdf.com"}\'', default=dict())
parser.add_argument("--enable-insecure-extension-access", action='store_true', help="launch.py 引数: 他のオプションに関係なく拡張機能を有効にするタブ")
parser.add_argument("--codeformer-models-path", type=normalized_filepath, help="launch.py 引数: コードフォーマーモデルファイルを含むディレクトリへのパス。", default=os.path.join(models_path, 'Codeformer'))
parser.add_argument("--gfpgan-models-path", type=normalized_filepath, help="launch.py 引数: GFPGANモデルファイルによるディレクトリへのパス。", default=os.path.join(models_path, 'GFPGAN'))
parser.add_argument("--esrgan-models-path", type=normalized_filepath, help="launch.py 引数: ESRGANモデルファイルを含むディレクトリへのパス。", default=os.path.join(models_path, 'ESRGAN'))
parser.add_argument("--bsrgan-models-path", type=normalized_filepath, help="launch.py 引数: BSRGANモデルファイルによるディレクトリへのパス。", default=os.path.join(models_path, 'BSRGAN'))
parser.add_argument("--realesrgan-models-path", type=normalized_filepath, help="launch.py 引数: RealESRGANモデルファイルでディレクトリへのパスを設置します。", default=os.path.join(models_path, 'RealESRGAN'))
parser.add_argument("--dat-models-path", type=normalized_filepath, help="launch.py 引数: DATモデルファイルを含むディレクトリへのパス。", default=os.path.join(models_path, 'DAT'))
parser.add_argument("--clip-models-path", type=normalized_filepath, help="launch.py 引数: CLIPモデルファイルを含むディレクトリへのパス。", default=None)
parser.add_argument("--xformers", action='store_true', help="launch.py 引数: クロスアテンションレイヤー用のxformerを有効にする")
parser.add_argument("--force-enable-xformers", action='store_true', help="launch.py 引数: チェックコードが実行可能と判断するかどうかに関わらず、クロスアテンションレイヤー用のxformerを有効にします。これがうまくいかない場合はバグ報告はしないでください")
parser.add_argument("--xformers-flash-attention", action='store_true', help="launch.py 引数: Flash Attentionで再現性を向上させるためにxformerを有効にする(SD2.xまたはそのバリアントのみ対応)")
parser.add_argument("--deepdanbooru", action='store_true', help="launch.py 引数: 何もしない")
parser.add_argument("--opt-split-attention", action='store_true', help="launch.py 引数: 自動的な最適化選択にはDoggettxのクロスアテンション層最適化を好む")
parser.add_argument("--opt-sub-quad-attention", action='store_true', help="launch.py 引数: 最適化を自動的に選択するためにメモリ効率の良い部分二次クロスアテンション層最適化を優先します")
parser.add_argument("--sub-quad-q-chunk-size", type=int, help="launch.py 引数: 部分二次クロスアテンション最適化で使用する query のチャンクサイズ", default=1024)
parser.add_argument("--sub-quad-kv-chunk-size", type=int, help="launch.py 引数: 部分二次クロスアテンション最適化で使用する KV のチャンクサイズ", default=None)
parser.add_argument("--sub-quad-chunk-threshold", type=int, help="launch.py 引数: 部分二次クロスアテンション最適化でチャンク分割を行う VRAM 使用率のしきい値（パーセント）", default=None)
parser.add_argument("--opt-split-attention-invokeai", action='store_true', help="launch.py 引数: 自動選択時に InvokeAI のクロスアテンション最適化を優先する")
parser.add_argument("--opt-split-attention-v1", action='store_true', help="launch.py 引数: 自動選択時に旧バージョンの split attention 最適化を優先する")
parser.add_argument("--opt-sdp-attention", action='store_true', help="launch.py 引数: 自動選択時に scaled dot product クロスアテンション最適化を優先する。PyTorch 2.* が必要")
parser.add_argument("--opt-sdp-no-mem-attention", action='store_true', help="launch.py 引数: 自動選択時にメモリ効率化を使わない scaled dot product クロスアテンション最適化を優先し、画像生成を決定的にする。PyTorch 2.* が必要")
parser.add_argument("--disable-opt-split-attention", action='store_true', help="launch.py 引数: 自動選択時にクロスアテンション最適化を使用しない")
parser.add_argument("--disable-nan-check", action='store_true', help="launch.py 引数: 生成画像や潜在空間に NaN が含まれるか確認しない。チェックポイントなしで CI を実行する場合に便利")
parser.add_argument("--use-cpu", nargs='+', help="launch.py 引数: 指定したモジュールで torch のデバイスとして CPU を使用する", default=[], type=str.lower)
parser.add_argument("--use-ipex", action="store_true", help="launch.py 引数: torch のデバイスとして Intel XPU を使用する")
parser.add_argument("--disable-model-loading-ram-optimization", action='store_true', help="launch.py 引数: モデル読み込み時の RAM 使用量を削減する最適化を無効にする")
parser.add_argument("--listen", action='store_true', help="0.0.0.0 をサーバー名として gradio を起動し、ネットワークからのリクエストを受け付ける")
parser.add_argument("--port", type=int, help="指定したサーバーポートで gradio を起動する。1024 未満のポートには管理者権限が必要。利用可能な場合のデフォルトは 7860", default=None)
parser.add_argument("--show-negative-prompt", action='store_true', help="launch.py 引数: 何もしません", default=False)
parser.add_argument("--ui-config-file", type=str, help="launch.py 引数: UI 設定に使用するファイル名", default=os.path.join(data_path, 'ui-config.json'))
parser.add_argument("--hide-ui-dir-config", action='store_true', help="launch.py 引数: webui からディレクトリ設定を隠す", default=False)
parser.add_argument("--freeze-settings", action='store_true', help="launch.py 引数: すべての設定の編集を全体的に無効にする", default=False)
parser.add_argument("--freeze-settings-in-sections", type=str, help='launch.py 引数: 設定ページの特定セクションの編集を無効にする。"saving-images,upscaling" のようにカンマ区切りで指定します。設定名の一覧は modules/shared_options.py にあります', default=None)
parser.add_argument("--freeze-specific-settings", type=str, help='launch.py 引数: "samples_save,samples_format" のようにカンマ区切りで指定した個別設定の編集を無効にする。設定名の一覧は config.json にあります', default=None)
parser.add_argument("--ui-settings-file", type=str, help="launch.py 引数: UI 設定に使用するファイル名", default=os.path.join(data_path, 'config.json'))
parser.add_argument("--gradio-debug",  action='store_true', help="--debug オプション付きで gradio を起動する")
parser.add_argument("--gradio-auth", type=str, help='launch.py 引数: gradio の認証を "username:password" 形式で設定する。複数指定する場合は "u1:p1,u2:p2,u3:p3" のようにカンマ区切りにする', default=None)
parser.add_argument("--gradio-auth-path", type=normalized_filepath, help='launch.py 引数: gradio の認証ファイルへのパス。例: "/path/to/auth/file"。形式は --gradio-auth と同じ', default=None)
parser.add_argument("--gradio-img2img-tool", type=str, help='launch.py 引数: 何もしません')
parser.add_argument("--gradio-inpaint-tool", type=str, help="launch.py 引数: 何もしません")
parser.add_argument("--gradio-allowed-path", action='append', help="launch.py 引数: gradio の allowed_paths にパスを追加し、そのパスのファイルを提供できるようにする", default=[data_path])
parser.add_argument("--opt-channelslast", action='store_true', help="launch.py 引数: Stable Diffusion のメモリ形式を channels last に変更する")
parser.add_argument("--styles-file", type=str, action='append', help="launch.py 引数: スタイルファイルのパスまたはワイルドカードパス。複数指定可能", default=[])
parser.add_argument("--use-textbox-seed", action='store_true', help="UI でシード入力にテキストボックスを使用する（上下ボタンはないが、長いシードを入力可能）", default=False)
parser.add_argument("--disable-console-progressbars", action='store_true', help="コンソールにプログレスバーを出力しない", default=False)
parser.add_argument("--enable-console-prompts", action='store_true', help="何もしません", default=False)  # Legacy compatibility, use as default value shared.opts.enable_console_prompts
parser.add_argument('--vae-path', type=normalized_filepath, help='VAE として使用するチェックポイント。この引数を設定すると VAE 関連の設定がすべて無効になります', default=None)
parser.add_argument("--disable-safe-unpickle", action='store_true', help="悪意のあるコードを含む可能性がある pytorch モデルの検査を無効にする", default=False)
parser.add_argument("--api", action='store_true', help="webui と一緒に API を起動するため api=True を使用する（API のみの場合は --nowebui を使用）")
parser.add_argument("--api-auth", type=str, help='API の認証を "username:password" 形式で設定する。複数指定する場合は "u1:p1,u2:p2,u3:p3" のようにカンマ区切りにする', default=None)
parser.add_argument("--api-log", action='store_true', help="api-log=True を使用してすべての API リクエストのログを有効にする")
parser.add_argument("--nowebui", action='store_true', help="webui の代わりに api=True を使用して API を起動する")
parser.add_argument("--ui-debug-mode", action='store_true', help="モデルを読み込まず、UI をすばやく起動する")
parser.add_argument("--device-id", type=str, help="使用するデフォルトの CUDA デバイスを選択する（事前に CUDA_VISIBLE_DEVICES=0,1 などの設定が必要な場合があります）", default=None)
parser.add_argument("--administrator", action='store_true', help="管理者権限", default=False)
parser.add_argument("--cors-allow-origins", type=str, help="許可する CORS オリジン。スペースなしのカンマ区切りで指定", default=None)
parser.add_argument("--cors-allow-origins-regex", type=str, help="許可する CORS オリジンを単一の正規表現で指定", default=None)
parser.add_argument("--tls-keyfile", type=str, help="TLS を部分的に有効にする。完全に機能させるには --tls-certfile が必要", default=None)
parser.add_argument("--tls-certfile", type=str, help="TLS を部分的に有効にする。完全に機能させるには --tls-keyfile が必要", default=None)
parser.add_argument("--disable-tls-verify", action="store_false", help="指定すると自己署名証明書を使用できるようにする", default=None)
parser.add_argument("--server-name", type=str, help="サーバーのホスト名を設定する", default=None)
parser.add_argument("--gradio-queue", action='store_true', help="何もしません", default=True)
parser.add_argument("--no-gradio-queue", action='store_true', help="gradio のキューを無効にする。ウェブページが WebSocket ではなく HTTP リクエストを使用するようになる。以前のバージョンではデフォルト")
parser.add_argument("--skip-version-check", action='store_true', help="torch と xformers のバージョンを確認しない")
parser.add_argument("--no-hashing", action='store_true', help="読み込み性能を向上させるため、チェックポイントの sha256 ハッシュ計算を無効にする", default=False)
parser.add_argument("--no-download-sd-model", action='store_true', help="--ckpt-dir にモデルが見つからない場合でも SD1.5 モデルをダウンロードしない", default=False)
parser.add_argument('--subpath', type=str, help='リバースプロキシと併用する gradio のサブパスを設定する')
parser.add_argument('--add-stop-route', action='store_true', help='何もしません')
parser.add_argument('--api-server-stop', action='store_true', help='API 経由でサーバーの停止、再起動、終了を有効にする')
parser.add_argument('--timeout-keep-alive', type=int, default=30, help='uvicorn の timeout_keep_alive を設定する')
parser.add_argument("--disable-all-extensions", action='store_true', help="他の設定に関係なく、すべての拡張機能の実行を防止する", default=False)
parser.add_argument("--disable-extra-extensions", action='store_true', help="組み込み拡張機能を除くすべての拡張機能の実行を防止する", default=False)
parser.add_argument("--skip-load-model-at-start", action='store_true', help="web 起動時のモデル読み込みをスキップする。--nowebui の場合のみ有効")
parser.add_argument("--unix-filenames-sanitization", action='store_true', help="ファイル名で '/' 以外の記号を許可する。ブラウザやファイルシステムと競合する可能性があります")
parser.add_argument("--filenames-max-length", type=int, default=128, help='保存画像のファイル名の最大長。変更するとファイルシステムと競合する可能性があります')
parser.add_argument("--no-prompt-history", action='store_true', help="前回生成時のプロンプトを読み込む機能を無効にする。この引数を設定すると '--data_path/params.txt' ファイルは作成されません")
